### ISSUE TITLE
AI rework TODO list

### ISSUE THREAD

**Issue by DaMatrix** [Team-Pepsi/pepsimod#10]
The pathfinder thing I made in pepsimod a long time ago is kind of a mess and rarely works. Seeing as how [Baritone](https://github.com/cabaletta/baritone) works a lot faster and better, and has more features, I want to rework pepsimod's AI to be able to work with that (and be able to do more than just pathfinding to a location).

- [ ] Totally nuke existing pathfinder code
- [ ] Reimplement all existing pepsimod AI features using Baritone
- [ ] Add more features making use of Baritone's features plus my own:
  - [ ] Automatic map art builder (using my old BetterMapArt project?)
  - [ ] Automatic crafting/sorting of specific items
  - [ ] User-defined white-/blacklist of storages that may be used by the bot
  - [ ] more? (will add if I have more ideas)
