### ISSUE TITLE
New features TODO list

### ISSUE THREAD

**Issue by DaMatrix** [Team-Pepsi/pepsimod#11]
A list of features I want to add to pepsimod which for whatever reason I never did xd

- [ ] Better pathfinding stuff (see #10)
- [ ] AntiAFK
- [ ] Speed
- [ ] Config synchronization across clients
- [ ] Inventory utils
  - [ ] Resupply
  - [ ] View total count of item type
  - [ ] Helper for keeping track of specific item type counts (in combination with storage whitelist thing from #10)
- [ ] More customizable HUD (draggable elements)
- [ ] Search
- [ ] Wallhack (i.e. Xray, but blocks are semitransparent instead of hidden)
